export const FINANCE_KEY_LABELS = {
  realProfit: "Reel Kar",
  theoryProfit: "Teoride Kar",
  bulkOrdersProfit: "KarS",
  shopifyProfit: "KarShopify",
  theoryTotalExpense: "Teori Toplam Gider",
  totalBusinessExpense: "Toplam İşletme Gideri",
  totalConstantExpense: "Tüm Sabit Gider",
  marketingExpense: "Tüm Reklam Gideri",
  totalDeliveriesCost: "Maliyet Sevkiyat",
  generalCost: "Maliyet Genel",
  totalOrderProductsCost: "Toplam Ürün Gideri",
  totalManualOrderProductsCost: "Maliyet MG",
  totalShopifyOrderProductsCost: "Maliyet MG Shopify",
  totalBulkOrderProductsCost: "Maliyet S",
  totalShopifyRevenue: "Ciro Shopify",
  totalBulkOrdersRevenue: "S Ciro",
  totalManualOrdersRevenue: "MG Ciro",
  totalStoreSaleRevenue: "Ciro Dükkan",
  totalTrendyolRevenue: "Ciro Trendyol",
  totalHepsiBuradaRevenue: "Ciro HepsiBurada",
  totalRevenue: "Tüm Ciro",
  bulkOrderBoxCost: "Kutu Maliyet S",
  manualOrderBoxCost: "Kutu Maliyet MG",
  shopifyOrderBoxCost: "Kutu Maliyet MG Shopify",
  bulkOrderCargoCost: "Kargo Maliyet S",
  manualOrderCargoCost: "Kargo Maliyet MG",
  shopifyOrderCargoCost: "Kargo Maliyet MG Shopify",
  totalCargoCost: "Kargo Maliyet",
  navlunCost: "Navlun Maliyet",
} as const;

export const FINANCE_USD_KEY_LABELS = ["shopifyOrderBoxCost"];
