export const FINANCE_KEY_LABELS: { [key: string]: string } = {
  realProfit: "Reel Kar",
  theoryProfit: "Teoride Kar",
  bulkOrdersProfit: "KarS",
  shopifyProfit: "KarShopify",
  theoryTotalExpense: "Teori Toplam Gider",
  totalBusinessExpense: "Toplam İşletme Gideri",
  totalConstantExpense: "Tüm Sabit Gider",
  marketingExpense: "Tüm Reklam Gideri",
  totalDeliveriesCost: "Maliyet Sevkiyat",
  generalCost: "Maliyet Genel",
  totalOrderProductsCost: "Toplam Ürün Gideri",
  totalManualOrderProductsCost: "Maliyet MG",
  totalShopifyOrderProductsCost: "Maliyet MG Shopify",
  totalBulkOrderProductsCost: "Maliyet S",
  totalShopifyRevenue: "Ciro Shopify",
  totalBulkOrdersRevenue: "S Ciro",
  totalManualOrdersRevenue: "MG Ciro",
  totalStoreSaleRevenue: "Ciro Dükkan",
  totalTrendyolRevenue: "Ciro Trendyol",
  totalHepsiBuradaRevenue: "Ciro HepsiBurada",
  totalRevenue: "Tüm Ciro",
};
