# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_SHOPPAR_BASE_URL: ${{ secrets.VITE_SHOPPAR_BASE_URL }}
          VITE_EVENTS_BASE_URL: ${{ secrets.VITE_EVENTS_BASE_URL }}
          
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SOURCE: '/dist'
          TARGET: ${{ secrets.TARGET_DIR }}
          ARGS: "-rltgoDzvO"
          EXCLUDE: "/node_modules/"
      
